version: '3.9'
services:
  discovery:
    build: ./discovery-service
    ports:
      - "8761:8761"
  gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
  ecom:
    build: ./Ecom
    environment:
      - SPRING_PROFILES_ACTIVE=
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecomdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234567890
    depends_on:
      - discovery
      - mysql
  inventory:
    build: ./inventory-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - discovery
  mysql:
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_DATABASE=ecomdb
    ports:
      - "3306:3306"
    command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
