version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  discovery-service:
    build:
      context: ./discovery-service
    image: discovery-service:latest
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  ecom-service:
    build:
      context: ./Ecom
    image: ecom-service:latest
    environment:
      - JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORDER_CONFIRMED_TOPIC=order.confirmed
    depends_on:
      - discovery-service

  inventory-service:
    build:
      context: ./inventory-service
    image: inventory-service:latest
    environment:
      - JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ORDER_CONFIRMED_TOPIC=order.confirmed
    depends_on:
      - discovery-service
      - kafka
