server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ecom-service
          uri: lb://Ecom
          predicates:
            - Path=/app/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true

# Eureka client (service discovery)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
