server:
  port: 8761

spring:
  application:
    name: discovery-service

# Standalone Eureka server (no self-registration)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
