name: CI Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Ecom
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build & test (Maven)
        run: mvn -B -DskipTests=false test package

  inventory:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: inventory-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build & test (Maven)
        run: ./mvnw -B -DskipTests=false test package

  frontend:
  discovery:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: discovery-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build (Maven)
        run: ./mvnw -B -DskipTests package

  gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-gateway
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Build (Maven)
        run: ./mvnw -B -DskipTests package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ecommerce-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ecommerce-frontend/package-lock.json
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Build
        run: npm run build


