name: Build & Publish Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND_NAME: ${{ github.repository }}-backend
  IMAGE_FRONTEND_NAME: ${{ github.repository }}-frontend
  IMAGE_INVENTORY_NAME: ${{ github.repository }}-inventory

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (backend)
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BACKEND_NAME }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: Ecom
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Extract metadata (frontend)
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_FRONTEND_NAME }}

      - name: Build and push frontend
      - name: Extract metadata (inventory)
        id: meta-inventory
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_INVENTORY_NAME }}

      - name: Build and push inventory
        uses: docker/build-push-action@v6
        with:
          context: inventory-service
          push: true
          tags: ${{ steps.meta-inventory.outputs.tags }}
          labels: ${{ steps.meta-inventory.outputs.labels }}
        uses: docker/build-push-action@v6
        with:
          context: ecommerce-frontend
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}


